---
# Role: dhcp
# Descrição: Instala e configura o isc-dhcp-server na máquina arq

- name: Instala o isc-dhcp-server
  ansible.builtin.package:
    name: isc-dhcp-server
    state: present

- name: Cria o arquivo dhcpd.conf com escopo e reservas fixas
  ansible.builtin.copy:
    dest: /etc/dhcp/dhcpd.conf
    content: |
      option domain-name "caua.cosme.devops";
      option domain-name-servers 1.1.1.1, 8.8.8.8;
      default-lease-time 600;
      max-lease-time 7200;
      ddns-update-style none;
      authoritative;
      subnet 192.168.56.0 netmask 255.255.255.0 {
        range 192.168.56.50 192.168.56.100;
        option routers 192.168.56.1;
      }

      host db {
        hardware ethernet 08:00:27:62:8e:98;
        fixed-address 192.168.56.50;
      }

      host app {
        hardware ethernet 08:00:27:79:b9:73;
        fixed-address 192.168.56.10;
      }

      host cli {
        hardware ethernet 08:00:27:79:42:66;
        fixed-address 192.168.56.13;
      }

  mode: '0644'

- name: Garante que o serviço DHCP está ativo
  ansible.builtin.service:
    name: isc-dhcp-server
    enabled: true
    state: restarted

