---
# Role: common
# Descrição: Tarefas comuns a todas as máquinas
# - Atualiza pacotes
# - Configura timezone
# - Instala o serviço NTP (chrony)
# - Cria grupo ifpb
# - Cria os usuários caua e cosme sem senha

- name: Atualiza lista de pacotes
  ansible.builtin.apt:
    update_cache: yes
    upgrade: yes

- name: Configura timezone para America/Recife
  ansible.builtin.timezone:
    name: America/Recife

- name: Instala o chrony
  ansible.builtin.package:
    name: chrony
    state: present

- name: Define servidor NTP como pool.ntp.br
  ansible.builtin.lineinfile:
    path: /etc/chrony/chrony.conf
    regexp: '^pool'
    line: 'pool pool.ntp.br iburst'
    state: present
    backup: yes

- name: Reinicia chrony
  ansible.builtin.service:
    name: chrony
    state: restarted
    enabled: true

- name: Cria o grupo ifpb
  ansible.builtin.group:
    name: ifpb
    state: present

- name: Cria usuário caua sem senha
  ansible.builtin.user:
    name: caua
    group: ifpb
    shell: /bin/bash
    state: present
    password: '*'

- name: Cria usuário cosme sem senha
  ansible.builtin.user:
    name: cosme
    group: ifpb
    shell: /bin/bash
    state: present
    password: '*'

- name: Cria o usuário nfs-ifpb (se não existir)
  user:
    name: nfs-ifpb
    uid: 2000
    shell: /usr/sbin/nologin
    state: present
  when: ansible_facts.uid_min is defined


